window.hjSiteSettings = window.hjSiteSettings || {"testers_widgets":[],"surveys":[],"heatmaps":[{"created_epoch_time":1463403856,"targeting":[{"negate":false,"pattern":"https:\/\/www.fiverr.com\/wordpress-pros","match_operation":"simple","component":"url"}],"id":528063},{"created_epoch_time":1460981636,"targeting":[{"negate":false,"pattern":"https:\/\/www.fiverr.com\/categories\/graphics-design\/","match_operation":"simple","component":"url"}],"id":476777}],"recording_capture_keystrokes":true,"polls":[],"site_id":176272,"record_targeting_rules":[{"negate":false,"pattern":"http:\/\/www.fiverr.com\/pages\/wordpress-pros","match_operation":"simple","component":"url"}],"forms":[],"record":true,"r":0.0175143618,"deferred_page_contents":[{"targeting":[{"negate":false,"pattern":"https:\/\/www.fiverr.com\/wordpress-pros","match_operation":"simple","component":"url"},{"negate":false,"pattern":"desktop","match_operation":"exact","component":"device"}],"id":1233754},{"targeting":[{"negate":false,"pattern":"https:\/\/www.fiverr.com\/wordpress-pros","match_operation":"simple","component":"url"},{"negate":false,"pattern":"tablet","match_operation":"exact","component":"device"}],"id":1233753},{"targeting":[{"negate":false,"pattern":"https:\/\/www.fiverr.com\/wordpress-pros","match_operation":"simple","component":"url"},{"negate":false,"pattern":"phone","match_operation":"exact","component":"device"}],"id":1233752},{"targeting":[{"negate":false,"pattern":"https:\/\/www.fiverr.com\/categories\/graphics-design\/","match_operation":"simple","component":"url"},{"negate":false,"pattern":"desktop","match_operation":"exact","component":"device"}],"id":1065709},{"targeting":[{"negate":false,"pattern":"https:\/\/www.fiverr.com\/categories\/graphics-design\/","match_operation":"simple","component":"url"},{"negate":false,"pattern":"tablet","match_operation":"exact","component":"device"}],"id":1065708},{"targeting":[{"negate":false,"pattern":"https:\/\/www.fiverr.com\/categories\/graphics-design\/","match_operation":"simple","component":"url"},{"negate":false,"pattern":"phone","match_operation":"exact","component":"device"}],"id":1065707}]};

window.hjBootstrap = window.hjBootstrap || function (scriptUrl) {
    var s = document.createElement('script');
    s.src = scriptUrl;
    document.getElementsByTagName('head')[0].appendChild(s);
    window.hjBootstrap = function() {};
};

hjBootstrap('https://script.hotjar.com/modules-5d1a8bf72bf05947875b5bb4e2648210.js');