application: looparticlerecommendations
version: 1
runtime: python27
api_version: 1
threadsafe: yes

instance_class: F1
automatic_scaling:
  min_idle_instances: 2
  max_idle_instances: 5
  min_pending_latency : 2s
  max_pending_latency: 5s
  max_concurrent_requests: 5


handlers:
- url: /css
  static_dir: css
  mime_type: "text/css"
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  mime_type: "icon/ico"

- url: .*
  script: main.app
 
 

libraries:
- name: webapp2
  version: "2.5.2"

